### ISSUE TITLE
Use Case Document

### ISSUE THREAD

**Issue by Anirudh-starhash** [Anirudh-starhash/Disster-Management-Project#2]

**Comment by Anirudh-starhash** [comment]
Need to be done by Merugu Pavan Kalyan

**Comment by MeruguPavanKalyan** [comment]
> Need to be done by Merugu Pavan Kalyan
I Have started the work . Will let you know the update asap .

**Comment by MeruguPavanKalyan** [comment]
Please Let me know the different actors of our system

**Comment by Anirudh-starhash** [comment]
Different Users are

Normal User -> Who uses the application
Admin -> Who monitors the application

Government Officials and Respective Authorities ,NGOs -> Who get information regarding disaster and give updates / alerts

Disaster Rescue Team -> Checks information and manages the disaster

**Comment by Anirudh-starhash** [comment]
> Different Users are
> 
> Normal User -> Who uses the application Admin -> Who monitors the application
> 
> Government Officials and Respective Authorities ,NGOs -> Who get information regarding disaster and give updates / alerts
> 
> Disaster Rescue Team -> Checks information and manages the disaster

One more Team which posts video regarding awareness on how, what to do during disaster
